### ISSUE TITLE
GHC (7.10.3) fails to install when cross-compiling.

### ISSUE THREAD

**Issue by Evi1M4chine** [gentoo-haskell/gentoo-haskell#475]
Hi. I have currently cross-built GHC from `armv7a-unknown-linux-gnueabi` to `armv7a-hardfloat-linux-gnueabi` (the compile phase succeeded), but the install phase fails because it can’t find `/var/tmp/portage/dev-lang/ghc-7.10.3/image//usr/lib/ghc-7.10.3/`. The reason is that the directory is actually  `/var/tmp/portage/dev-lang/ghc-7.10.3/image//usr/lib/armv7a-hardfloat-linux-gnueabi-ghc-7.10.3`.

I tried to see if I can fix the ebuild itself, but apparently src_install isn’t even executed (yet?) at the failing point. In any case, nothing I change in there seems to have an effect. (I have checked if it’s really the correct file I’m editing.)
So I probably can’t fix it myself.

Could you change the ebuild so that it can handle the different path for cross-compilation? Or alternatively, if there is a better way, help me do that?

This is how I built it:
1. I applied [a simple patch to make it accept “hardfloat”](http://lpaste.net/14987). (By putting it in `/etc/portage/patches/dev-lang/ghc/`, and adding `epatch_user` to the ebuild.
2. I emerged LLVM 3.3-rc1. (Everything above makes the build fail.)
3. I installed [the pre-built GHC from haskell.org](https://www.haskell.org/ghc/download_ghc_7_10_3#linux_armv7) to `/opt/ghc-7.10.3` and added its `./bin` to `PATH`.
4. I made sure there was 1GB of swap (with a swappiness of 60) on top of the 1GB RAM of the ARM box.
4. Finally, I ran `CHOST="armv7a-unknown-linux-gnueabi" CBUILD="armv7a-unknown-linux-gnueabi" CTARGET="armv7a-hardfloat-linux-gnueabi" ebuild /usr/local/portage/dev-lang/ghc/ghc-7.10.3.ebuild merge`
The rest of the system is built as `armv7a-hardfloat-linux-gnueabi`.

This is the relevant end of the build log (manually translated back from German):

```
/usr/lib/portage/python2.7/ebuild-helpers/xattr/install -c -m 755  libraries/gen_contents_index "/var/tmp/portage/dev-lang/ghc-7.10.3/image/usr/share/doc/ghc-7.10.3/html/libraries/"
mv: the execution of stat for „/var/tmp/portage/dev-lang/ghc-7.10.3/image//usr/lib/ghc-7.10.3/package.conf.d/*.conf“ is not possible: File or directory not found
```

**Comment by trofi** [comment]
Your cross-compiler case is lucky :) AFAIU you can run ${CTARGET} bianries directly on host.

I've pushed
    https://github.com/gentoo-haskell/gentoo-haskell/commit/4020ca0bde236f68229abe3183ad29fb66b43b26
to handle ${CHOST} prefix but I checked only single thing: it does not yet break native build.

**Comment by Evi1M4chine** [comment]
@trofi: Indeed :) I knew what I was doing though. This *is* an `armv7a-hardfloat-linux-gnueabi` system But the only binary GHC I could find to bootstrap my GHC emerge, could only output `armv7a-unknown-linux-gnueabi`. So I had to lie to it a bit, to get me a compiler that can output hardfloat, to use as a proper binary GHC to bootstrap a proper full hardfloat GHC with.
(The problem is that I actually don’t know it this actually results in a hardfloat compiler too, or the “hardfloat” in there is just ignored.)
The above combination of CHOST/CBUILD/CTARGET is the only one that it let me build with, so that’s what I picked. :)

Thank you for the patch. I’ll try it right away. :)

**Comment by Evi1M4chine** [comment]
I just tested it, and: Yes, it still fails with the same error.

**Comment by Evi1M4chine** [comment]
BTW: Quickly running
````
cd /var/tmp/portage/dev-lang/ghc-7.10.3/image/usr/lib/
ln -s armv7a-hardfloat-linux-gnueabi-ghc-7.10.3 ghc-7.10.3
````
in another shell *during* the install phase, allows the installation to succeed! (The Cabal package registering gives one some time to do this manually.)

Then after installation, one has to make softlinks for every `/usr/bin/armv7a-hardfloat-linux-gnueabi-*` in the package to the equivalent `/usr/bin/*`. (I additionally made sure that every `/usr/bin/*-7.10.3` of the package also softlinked to `/usr/bin/*`.)

I will now try if this suffices to build GHC properly, without the `/opt/ghc-7.10.3` crutch GHC.

I cannot find the place in the ebuild to change to do any of it automatically. It seems to be hidden in some eclasses, which are beyond my Portage skills currently. I wish someone who knows those classes could fix this… :/

**Comment by trofi** [comment]
https://github.com/gentoo-haskell/gentoo-haskell/commit/4020ca0bde236f68229abe3183ad29fb66b43b26was expected to fix path to package.conf.d but 'ebuild... merge' does not catch ebuild changes unless you restart (ebuild clean) merge process from scratch (i didn't expect you have to do any src_install() tweaks).

If it was a clean merge after the sync please grab whole build.log and we'll try to figure out what else needs fixing.

As for using non-standard ghc in future i'd like to change hardcoded 'type -p ghc' (and ghc-pkg) (https://github.com/gentoo-haskell/gentoo-haskell/blob/master/eclass/ghc-package.eclass#L19) to something that respects $HC and HC_PKG variables if present.

**Comment by Evi1M4chine** [comment]
I *did* replace that .ebuild file that was in a `/var/tmp/portage/dev-lang/ghc-7.10.3/` subdirectory, assuming that would allow me to continue without building, as a build takes more than a day if I’m unlucky.

The error was exactly the same. But you are right: No changes did seem to have any effect. So it probably didn’t work as expected.

I’m currently emerging GHC normally though, using the previously hack-installed GHC as mentioned above. Up to now, everything seems to be going well, and I set FEATURES="-collision-protect", so it overwrites the symlinks I created manually.

Therefore, if this succeeds, this case would be closed for me.
I would also assume the ebuild is fine.

Btw: We really need those pre-build binary packages, so bootstrapping and this whole hassle doesn’t become necessary in the first place. Since I succeeded, I’m daring to assume this should not be a problem. But if it is, I am willing to assist.

**Comment by trofi** [comment]
I think it's not enough to replace ebuild as all ebuild contents is stored in environment file.

**Comment by Evi1M4chine** [comment]
Just for those who are curious: It really succeeded! It took (<)3GB of swap space to do with two threads. I even compiled it a second time (due to a unrelated change) using my fresh Gentoo-aligned GHC installation.

The only problem is that somehow the /usr/bin/ghc-7.10.3 softlink is still required for it to work. No idea why it didn’t just overwrite it, or if I can replace it by the file it links to and remove that file?

In any case: I now have a full working Haskell Platform on this little hardfloat ARM SBC, and so can you! :)

Would it help to quickpkg this and distribute it as the binary compiler used by GHC during normal (hardfloat) installs?
Then all this hassle won’t be necessary anymore and we can close this bug for good. :)

(A softfloat binary package already exists. The upstream GHC one or the Debian one can be used. Meaning we’d have full ARMv7 support.)

**Comment by trofi** [comment]
I think newer ghc versions work ok as-is. I Cross-built ghc-8.8.1 to `powerpc64le` recently and it worked as-is. Let's close it as solved.
